export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT = 'LOGOUT'
export const LOCK = 'LOCK'

export const CURRENCY_REQUEST = 'CURRENCY_REQUEST'
export const CURRENCY_SUCCESS = 'CURRENCY_SUCCESS'
export const CURRENCY_ERROR = 'CURRENCY_ERROR'

export const RECIPIENT_REQUEST = 'RECIPIENT_REQUEST'
export const RECIPIENT_SUCCESS = 'RECIPIENT_SUCCESS'
export const RECIPIENT_ERROR = 'RECIPIENT_ERROR'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'